name: CI

on:
  push:
    branches:
      - main

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y libgtk-3-dev libxss-dev libgconf-2-4 libnss3 libasound2
          npm install
      - name: Build electron app
        run: |
          npm run buildLinux
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: buildLinux
          path: distLinux

  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build electron app
        run: |
          npm run buildWindows
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: buildWindows
          path: distWindows

  build_on_mac_x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build electron app
        run: |
          npm run buildMac64
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: buildMac64
          path: distMac64

  build_on_mac_arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build electron app
        run: |
          npm run buildMacARM
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: buildMacARM
          path: distMacARM